services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
      - proxy

  backend:
    build: 
      context: ./backend
      target: prod
    container_name: zig_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/db
      JWT_SECRET: p0jrMzCSas7yxiE8vu5BQ92TVk5ucEdQjF1kXfzdYl5XXe6JMDUIxeoWLuegKiiAcAYvoekGIFdzATZnNT_A0Q
    ports:
      - "8080:8080"
    networks:
      - app_network
      - proxy

  solver:
    build:
      context: ./solver
      target: prod
    container_name: zig_solver
    restart: always
    ports:
      - "8081:8081"
    networks:
        - app_network
        - proxy

  frontend:
    build: 
      context: ./frontend
      target: prod
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vite.rule=Host(`scrabble.brimveyn.dev`)"
      - "traefik.http.services.vite.loadbalancer.server.port=5173"
      - "traefik.http.routers.vite.entrypoints=http"
      - "traefik.http.routers.vite-secure.entrypoints=https"
      - "traefik.http.routers.vite-secure.rule=Host(`scrabble.brimveyn.dev`)"
      - "traefik.http.routers.vite-secure.tls=true"
      - "traefik.http.routers.vite-secure.tls.certresolver=cloudflare"

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
  proxy:
    external: true

