version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: 
      context: ./backend
      target: prod
    container_name: zig_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_PORT: 5432
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db

    ports:
      - "8080:8080"
    networks:
      - app_network

  frontend:
    build: 
      context: ./frontend
      target: prod
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4430:4430"
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge

